### ISSUE TITLE
upload-artifact@v3 deprecation

### ISSUE THREAD

**Issue by tough-griff** [Contrast-Security-OSS/contrast-sca-action#33]
This action uses `actions/upload-artifact@v3`, which is deprecated.

> **Deprecation notice: v1, v2, and v3 of the artifact actions**
The following artifacts were uploaded using a version of actions/upload-artifact that is scheduled for deprecation: "fingerPrint.log", "fingerPrintInfo.json", "package-lock.json.contrast.log".
Please update your workflow to use v4 of the artifact actions.
Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

From the link above, this action will no longer be usable starting November 30, 2024.
> Starting November 30, 2024, GitHub Actions customers will no longer be able to use v3 of [actions/upload-artifact](https://github.com/actions/upload-artifact) or [actions/download-artifact](https://github.com/actions/download-artifact). Customers should update workflows to begin using [v4 of the artifact actions](https://github.blog/2024-02-12-get-started-with-v4-of-github-actions-artifacts/) as soon as possible. While v4 of the artifact actions improves upload and download speeds by up to 98% and includes several new features, there are [key differences](https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes) from previous versions that may require updates to your workflows. Please see [the documentation](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md) in the project repositories for guidance on how to migrate your workflows.

This will cause workflow failures for anyone leveraging this action.

**Comment by tough-griff** [comment]
`v4` does have the breaking change where you can no longer upload multiple artifacts of the same name. Since our internal workflows calling this action (at least the NodeJS ones I've seen) use the action in a matrix, the uploaded files should probably attach some sort of prefix.

**Comment by wrngrn** [comment]
Closed out with v3 of this action we are now using upload action@v4.
A random suffix will be generated to support the matrix run and prevent uploading with the same name.
The user can set this to a determinate string by passing --modifier
